name: 'blog'
title: '我的博卡-MyBoKa'
system: ''

#数据库配置
db_address: 'localhost'
db_ip: 27017

#默认用户注册就拥有的模板
default_templates:
  content_templates:
    - 'simple_text'
    - 't_comment'
  blog_template:
    first: 'default_blog'


comment_template: 't_comment'

#新上传的模板放置位置
zip_template_path: '/home/gen/www/zipfile'
#缓存位置
temp_zip_path: '/home/gen/www/tempfile'

default_temp_icon: 'default/default_icon.png'
static_temp_site: 'http://static.myboka.com'
#动态文件路径
dynamic_file_path: '/home/gen/www/dynamic_template'
#静态文件路径
static_file_path: '/home/gen/www/static'

carte_site: 'http://mingp.net/'

home_domain:
  - 'myboka.com'
  - 'myboka.net'
  - 'myboka.cn'
  - 'localhost'
host_domain:
  - 'myboka.com'
  - 'myboka.net'
  - 'myboka.cn'