Session.ensure_index(:login_token)
Template.ensure_index(:name)
User.ensure_index([[:name, 1], [:email, 1]])
Confirm.ensure_index(:token)
Findback.ensure_index(:token)
ElementComment.ensure_index(:element_id)
Tag.ensure_index(:label)
Tag.ensure_index(:index_score)
Article.ensure_index(:score)
Article.ensure_index(:title)
ArticleGroup.ensure_index(:name)